### ISSUE TITLE
Prose editor display can be improve on admin panel

### ISSUE THREAD

**Issue by zft9xgy** [matthiask/django-prose-editor#7]
First, thank for create this, your work and dedication.

The prose editor is display like this in the admin panel:
<img width="1452" alt="Captura de pantalla 2024-07-18 a las 22 38 48" src="https://github.com/user-attachments/assets/3b79a42c-6c22-4186-8c6a-9e4646a60374">

What i suggest is to set min-height and a margin-bottom to improve first look.

`src/css/editor.css`

```css
.ProseMirror {
  /* 
 Existing attributes
*/
  min-height: 30vh;
}

.prose-editor {
 /* 
 Existing attributes
*/
  margin-bottom: 10px;
}
```

In my opinion this will display a better text box.

<img width="1433" alt="Captura de pantalla 2024-07-18 a las 23 11 47" src="https://github.com/user-attachments/assets/61e53121-c3dc-4a36-baa9-45cbeb1c13d2">
